# Load packages ----------------------------------------------------------------
library(pksensi)
library(ggpubr)
library(cowplot)

# Create mod.exe ---------------------------------------------------------------
source("MCSim/function.R")
set_PATH()
makemod()

# Compile model code -----------------------------------------------------------
model <- "bupropion_CAT.model" 
makemcsim(model)

# Define log-uniform function---------------------------------------------------
qlunif <- function(p, min, max, base=exp(1)) {
  if (mode(p) != "numeric")
    stop("'p' must be a non-empty numeric vector")
  if (any(missing(min), missing(max)))
    stop("'min' and 'max' not provided, without default.\n")
  return(base ^ (log(min, base) + (log(max, base) - log(min, base)) * p))
}

# Define input conditions ------------------------------------------------------
times <- c(0.25,  0.50,  0.75,  1.00,  1.50,  2.00,  3.00,  
           4.00,  6.00,  8.00, 24.00, 48.00, 72.00, 96.00)

output <- c("lnC_central_ngml") # Can not use natural scale to find the influential parameters... 
n <- 8000

parameters <- c(
  "Weibull_scale_IR",
  #"Weibull_scale_ER",
  #"Weibull_slope_ER",
  "sc_F_total",
  "f_Flow_stom",
  "f_Flow_duod",
  "f_Flow_jeju",
  "f_Flow_ileum",
  "f_Flow_cecum",
  "f_Flow_colon",
  "f_Flow_liver",
  "f_BDM_stom",
  "f_BDM_duod",
  "f_BDM_jeju",
  "f_BDM_ileum",
  "f_BDM_cecum",
  "f_BDM_colon",
  "f_BDM_liver",
  "f_BDM_stom_lu",
  "f_BDM_duod_lu",
  "f_BDM_jeju_lu",
  "f_BDM_ileum_lu",
  "f_BDM_cecum_lu",
  "f_BDM_colon_lu",
  "Length_stom",
  "Length_duod",
  "Length_jeju",
  "Length_ileum",
  "Length_cecum",
  "Length_colon",
  "Radius_stom",
  "Radius_duod",
  "Radius_jeju",
  "Radius_ileum",
  "Radius_cecum",
  "Radius_colon",
  "T12_stom_lu", 
  "T12_duod_lu",
  "T12_jeju_lu",
  "T12_ileum_lu",
  "T12_cecum_lu",
  "T12_colon_lu",
  "pH_stom",
  "pH_duod",
  "pH_jeju",
  "pH_ileum",
  "pH_cecum",
  "pH_colon",
  "MicroProt_stom",
  "MicroProt_duod",
  "MicroProt_jeju",
  "MicroProt_ileum",
  "MicroProt_cecum",
  "MicroProt_colon",
  "MicroProt_liver",
  "H_ep",
  "pKa",
  "G_Radius",
  "G_Density",
  "Solubility",
  "Peff", 
  "K_precip",
  "Ratio_BP",
  "Fu_plasma",  
  "Fu_stom", 
  "Fu_duod", 
  "Fu_jeju", 
  "Fu_ileum", 
  "Fu_cecum", 
  "Fu_colon", 
  "Fu_liver", 
  "Fu_vitro_stom", 
  "Fu_vitro_duod", 
  "Fu_vitro_jeju", 
  "Fu_vitro_ileum", 
  "Fu_vitro_cecum", 
  "Fu_vitro_colon", 
  "Fu_vitro_liver",
  "Kpuu_stom",
  "Kpuu_duod",
  "Kpuu_jeju",
  "Kpuu_ileum",
  "Kpuu_cecum",
  "Kpuu_colon",
  "Kpuu_liver",
  "V_central_LKg", 
  "Kc2p", 
  "Kp2c", 
  "Vmax_met_vitro_intestine",
  "Vmax_met_vitro_liver"
)

q <- c(
  "qunif",
  #"qunif",
  #"qunif",
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif",
  "qunif",
  "qunif",
  "qunif",
  "qunif",
  "qunif",
  "qunif",
  "qunif",
  "qunif",
  "qunif",
  "qunif",
  "qunif",
  "qunif",
  "qunif",
  "qunif",
  "qunif",
  "qunif",
  "qunif",
  "qunif",
  "qunif",
  "qunif",
  "qunif",
  "qunif",
  "qunif",
  "qunif",
  "qunif",
  "qunif", 
  "qlunif", 
  "qunif", 
  "qlunif",
  "qunif",
  "qlunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif", 
  "qunif",
  "qunif", 
  "qunif",
  "qunif", 
  "qunif", 
  "qlunif", 
  "qlunif"
)

q.arg <- list(
  list(min = 0.1,   max = 4.0),
  #list(min = 3.0,   max = 4.0),
  #list(min = 1.0,   max = 1.5),
  list(min = 10.5, max = 19.5),
  list(min = 0.019, max = 0.029),
  list(min = 0.011, max = 0.021),
  list(min = 0.051, max = 0.061),
  list(min = 0.028, max = 0.038),
  list(min = 0.001, max = 0.011),
  list(min = 0.033, max = 0.043),
  list(min = 0.2, max = 0.3),
  list(min = 0.0016, max = 0.0026),
  list(min = 0.0001, max = 0.0005),
  list(min = 0.0004, max = 0.0014),
  list(min = 0.0001, max = 0.0011),
  list(min = 0.0001, max = 0.0009),
  list(min = 0.0043, max = 0.0053),
  list(min = 0.0139, max = 0.0293),
  list(min = 0.031, max = 0.041),
  list(min = 0.0003, max = 0.001),
  list(min = 0.0018, max = 0.0028),
  list(min = 0.0027, max = 0.0037),
  list(min = 0.0001, max = 0.001),
  list(min = 0.0046, max = 0.0056),
  list(min = 1.981, max = 3.679),
  list(min = 0.987, max = 1.833),
  list(min = 8.176, max = 15.184),
  list(min = 12.264, max = 22.776),
  list(min = 1.19, max = 2.21),
  list(min = 7.7, max = 14.3),
  list(min = 0.6769, max = 1.2571),
  list(min = 0.1071, max = 0.1989),
  list(min = 0.0959, max = 0.1781),
  list(min = 0.0686, max = 0.1274),
  list(min = 0.245, max = 0.455),
  list(min = 0.175, max = 0.325),
  list(min = 0.1,   max = 0.4),
  list(min = 0.1, max = 0.4),
  list(min = 0.408, max = 1.632),
  list(min = 0.816, max = 3.264),
  list(min = 1.82, max = 7.28),
  list(min = 5.4, max = 21.6),
  list(min = 1.2, max = 2.2),
  list(min = 5.5, max = 6.5),
  list(min = 6, max = 7),
  list(min = 6.9, max = 7.9),
  list(min = 5.4, max = 6.4),
  list(min = 6.5, max = 7.5),
  list(min = 0, max = 10),
  list(min = 13, max = 23),
  list(min = 20, max = 30),
  list(min = 0, max = 10),
  list(min = 0, max = 10),
  list(min = 0, max = 10),
  list(min = 40, max = 50),
  list(min = 0.00032, max = 0.00042),
  list(min = 8.0, max = 9.0),
  list(min = 10, max = 100), 
  list(min = 1.0, max = 1.8),
  list(min = 10000, max = 100000), 
  list(min = 0.05,  max = 0.31),
  list(min = 0.4, max = 40),
  list(min = 0.72, max = 0.92),
  list(min = 0.06, max = 0.26),
  list(min = 0.06, max = 0.26),
  list(min = 0.06, max = 0.26),
  list(min = 0.06, max = 0.26),
  list(min = 0.06, max = 0.26),
  list(min = 0.06, max = 0.26),
  list(min = 0.06, max = 0.26),
  list(min = 0.06, max = 0.26),
  list(min = 0.06, max = 0.26),
  list(min = 0.06, max = 0.26),
  list(min = 0.06, max = 0.26),
  list(min = 0.06, max = 0.26),
  list(min = 0.06, max = 0.26),
  list(min = 0.06, max = 0.26),
  list(min = 0.06, max = 0.26),
  list(min = 0.5,   max = 5),
  list(min = 0.5,   max = 5),
  list(min = 0.5,   max = 5),
  list(min = 0.5,   max = 5),
  list(min = 0.5,   max = 5),
  list(min = 0.5,   max = 5),
  list(min = 0.5,   max = 5),     # non-informative; U(0.5,5)
  list(min = 1.5,   max = 28.5),  # N(15, 4.5) 
  list(min = 0.01,  max = 0.19),  # N(0.1, 0.03) 
  list(min = 0.004, max = 0.076), # N(0.04, 0.012)
  list(min = 1e-5,  max = 1e-3),  
  list(min = 1e-5,  max = 1e-3)
)     

set.seed(1234)
x <- rfast99(params = parameters, n = n, q = q, q.arg = q.arg, 
             rep = 1) # Use higher rep to check convergence
gc()

conditions <- c("G_delayed_u = 1", 
                "R_type = 0", 
                "Weibull_slope_IR = 1", 
                "Q_to_release = 417.1185")

mfile <- "bupropion_CAT.model"

# Need 4 cores to conduct parallel computing
y <- solve_mcsim(x, mName = mfile, params = parameters,
                 vars = output, time = times, 
                 condition = conditions,
                 rtol = 1e-8, atol = 1e-8, parallel = TRUE) 

# Plot -------------------------------------------------------------------------
#tiff("plots/fig5.tiff", res=600, compression = "lzw", height = 6, width = 10, units="in")
pdf("plots/fig5.pdf", height = 6, width = 10)
heat_check(y, SI.cutoff = c(0.05, 0.1), order = "total order", text = T) + 
  theme_pubr() + labs(x="Time, hr", y="", title = "Total sensitivity index") +
  theme(strip.background = element_blank(),
        strip.text = element_blank(),
        legend.title = element_blank())
dev.off()
#ggsave("plots/fig5.jpeg", dpi = 300, height = 6, width = 10, units="in")

